#Deploy configmap for DB Host, User, Port, Database and App Colour
apiVersion: v1

kind: ConfigMap

metadata:

  name: app-config

data:

  DB_USER: root

  DB_HOST: "db-service"

  DB_PORT: "3306"

  DATABASE: "employees"
  
  APP_COLOR: "blue"
